export const typeColors = {
  normal: {
    bg: "bg-gray-400",
    text: "text-gray-600",
    badge: "bg-gray-400 text-white",
    bar: "bg-gray-400",
  },
  fire: {
    bg: "bg-red-500",
    text: "text-red-600",
    badge: "bg-red-500 text-white",
    bar: "bg-red-500",
  },
  water: {
    bg: "bg-blue-500",
    text: "text-blue-600",
    badge: "bg-blue-500 text-white",
    bar: "bg-blue-500",
  },
  electric: {
    bg: "bg-yellow-400",
    text: "text-yellow-600",
    badge: "bg-yellow-400 text-black",
    bar: "bg-yellow-400",
  },
  grass: {
    bg: "bg-green-500",
    text: "text-green-600",
    badge: "bg-green-500 text-white",
    bar: "bg-green-500",
  },
  ice: {
    bg: "bg-cyan-400",
    text: "text-cyan-600",
    badge: "bg-cyan-400 text-black",
    bar: "bg-cyan-400",
  },
  fighting: {
    bg: "bg-orange-600",
    text: "text-orange-700",
    badge: "bg-orange-600 text-white",
    bar: "bg-orange-600",
  },
  poison: {
    bg: "bg-purple-500",
    text: "text-purple-600",
    badge: "bg-purple-500 text-white",
    bar: "bg-purple-500",
  },
  ground: {
    bg: "bg-amber-600",
    text: "text-amber-700",
    badge: "bg-amber-600 text-white",
    bar: "bg-amber-600",
  },
  flying: {
    bg: "bg-sky-400",
    text: "text-sky-600",
    badge: "bg-sky-400 text-black",
    bar: "bg-sky-400",
  },
  psychic: {
    bg: "bg-pink-500",
    text: "text-pink-600",
    badge: "bg-pink-500 text-white",
    bar: "bg-pink-500",
  },
  bug: {
    bg: "bg-lime-500",
    text: "text-lime-600",
    badge: "bg-lime-500 text-white",
    bar: "bg-lime-500",
  },
  rock: {
    bg: "bg-stone-500",
    text: "text-stone-600",
    badge: "bg-stone-500 text-white",
    bar: "bg-stone-500",
  },
  ghost: {
    bg: "bg-indigo-600",
    text: "text-indigo-700",
    badge: "bg-indigo-600 text-white",
    bar: "bg-indigo-600",
  },
  dragon: {
    bg: "bg-violet-600",
    text: "text-violet-700",
    badge: "bg-violet-600 text-white",
    bar: "bg-violet-600",
  },
  dark: {
    bg: "bg-neutral-800",
    text: "text-neutral-800",
    badge: "bg-neutral-800 text-white",
    bar: "bg-neutral-800",
  },
  steel: {
    bg: "bg-slate-400",
    text: "text-slate-600",
    badge: "bg-slate-400 text-black",
    bar: "bg-slate-400",
  },
  fairy: {
    bg: "bg-rose-400",
    text: "text-rose-600",
    badge: "bg-rose-400 text-black",
    bar: "bg-rose-400",
  },
};
